---
title: "intro_ggplot"
author: "Jill MacKay"
date: "03/12/2020"
output: html_document
---

# Set Up

```{r}
library(tidyverse)
```

# Beginning to think about ggplot

```{r}

View(mtcars)

```


```{r}

mtcars %>%
  summarise(mean_gears = mean(gear))

```


```{r}

mtcars %>% 
  ggplot(aes(x = mpg, y = disp))

```


```{r}

mtcars %>%
  ggplot(aes(x = mpg, y = disp)) +
  geom_point()

```

```{r}

mtcars %>% 
  ggplot(aes(x = mpg, y = disp)) + 
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5))

```



```{r}

mtcars %>% 
  ggplot(aes(x = mpg, y = disp)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50))


```


```{r}
mtcars %>% 
  ggplot(aes(x = mpg, y = disp)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) + 
  theme_minimal()
```



```{r}
mtcars %>% 
  ggplot(aes(x = mpg, y = disp)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) +
  labs(x = "Miles per US Gallon",
       y = "Displacement (cu.in.)",
       title = "Displacement of US Cars by Miles Per Gallon",
       subtitle = "Data from Henderson & Velleman (1981)")


```


```{r}
mtcars %>% 
  ggplot(aes(x = mpg, y = disp)) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) +
  labs(x = "Miles per US Gallon",
       y = "Displacement (cu.in.)",
       title = "Displacement of US Cars by Miles Per Gallon",
       subtitle = "Data from Henderson & Velleman (1981)") +
  stat_smooth(method = "lm")


```

```{r}

mtcars %>% 
  ggplot(aes(x = mpg, y = disp, colour = as.factor(am))) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) +
  labs(x = "Miles per US Gallon",
       y = "Displacement (cu.in.)",
       title = "Displacement of US Cars by Miles Per Gallon",
       subtitle = "Data from Henderson & Velleman (1981)") +
  stat_smooth(method = "lm")


```



```{r}


plot1 <- mtcars %>% 
  ggplot(aes(x = mpg, y = disp, colour = as.factor(am))) +
  geom_point() +
  scale_x_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 5)) +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) +
  labs(x = "Miles per US Gallon",
       y = "Displacement (cu.in.)",
       title = "Displacement of US Cars by Miles Per Gallon",
       subtitle = "Data from Henderson & Velleman (1981)") +
  stat_smooth(method = "lm") +
  scale_color_manual(values = c("#999999", "#E69F00"),
                     name = "Transmission type",
                     breaks = c(0, 1),
                     labels = c("Automatic", "Manual"))

```


# Different types of geom

```{r}

mtcars %>% 
  ggplot(aes(x = as.factor(am), y = disp)) +
  geom_boxplot()

mtcars %>% 
  ggplot(aes(x = am, y = disp, group = am)) +
  geom_boxplot()

```


```{r}

mtcars %>% 
  ggplot(aes(x = as.factor(am), y = disp, colour = as.factor(am))) +
  geom_boxplot() +
  labs (title = "My lovely chart",
        x = "Transmission Type", 
        y = "Displacement") +
  theme(legend.position = "none")


```



# Faceting

```{r}

mtcars %>% 
  ggplot(aes(x = as.factor(am), y = disp)) +
  geom_bar(stat = "summary") +
  facet_wrap(facets = ~ gear)



```
